export * from "./gen/ecore.g.js"
export { readEcoreFile } from "./reader.js"
export type { ExternalETypeResolver, ReaderOptions } from "./reader.js"
export { ecoreStdlib } from "./stdlib.js"
export { asLionWebLanguage } from "./transformer.js"
export type { TransformerOptions } from "./transformer.js"
