export * from "./gen/ecore.g.js"
export { readEcoreFile } from "./reader.js"
export type { ExternalETypeResolver, ReaderOptions } from "./reader.js"
export { asLionWebLanguage } from "./transformer.js"
export type { TransformationOptions } from "./transformer.js"
